Expose a "service worker timing info" struct
w3c/ServiceWorker pull request #1581
Opened 2021-04-15 13:11 UTC by noamr

to report worker-specific timing information to Navigation Timing.

In preparation for https://github.com/w3c/ServiceWorker/pull/1575

2021-04-23 08:30 UTC, jakearchibald approved these changes
LGTM!

2021-04-23 08:30 UTC, jakearchibald requested changes
But, waiting on IPR. Give me a shout when that happens.

2021-04-23 08:42 UTC, noamr commented
> But, waiting on IPR. Give me a shout when that happens.

Thanks! I applied for Invited Expert a week ago, how do I find out where it stands?

2021-04-23 14:54 UTC, ylafon commented
Hi @noamr I sent you a one-off IPR declaration, if you plan to do more contribution then sure, being an IE will be more efficient.

2021-04-23 15:39 UTC, noamr commented
> Hi @noamr I sent you a one-off IPR declaration, if you plan to do more contribution then sure, being an IE will be more efficient.

I have this and an additional PR pending. Not sure how much I plan to contribute in the future. Would a one-off PR declaration suffice for 2 PRs?

2021-04-23 15:45 UTC, ylafon commented
@jakearchibald IPR cleared.
And it seems that IPR status is good also for #1575 (if not, ping me there)

2021-04-27 12:41 UTC, noamr commented
@jakearchibald ping for merge?

2021-04-27 13:13 UTC, jakearchibald approved these changes

2021-04-27 13:13 UTC, merged

2021-04-27 13:13 UTC, jakearchibald commented
Thanks for the ping. I'd missed this.